<a href="https://colab.research.google.com/github/yamada2310/dataAnalysis100/blob/main/dataAnalysis100_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir('/content/drive/MyDrive/100knock-data_analytics/3ç« ')

In [3]:
import pandas as pd
uselog = pd.read_csv('use_log.csv')
print(len(uselog))
uselog.head()

197428

            log_id customer_id     usedate
0  L00000049012330    AS009373  2018-04-01
1  L00000049012331    AS015315  2018-04-01
2  L00000049012332    AS040841  2018-04-01
3  L00000049012333    AS046594  2018-04-01
4  L00000049012334    AS073285  2018-04-01

In [4]:
customer = pd.read_csv('customer_master.csv')
print(len(customer))
customer.head()

4192

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0
2,OA974876,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0
3,HD024127,XXXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0
4,HD661448,XXXXX,C03,F,2015-05-01 00:00:00,NaN,CA1,0

In [5]:
class_master = pd.read_csv('class_master.csv')
print(len(class_master))
class_master.head()

3

  class class_name  price
0   C01     ãªã¼ã«ã¿ã¤ã   10500
1   C02      ãã¤ã¿ã¤ã    7500
2   C03        ãã¤ã   6000

In [6]:
campaign_master = pd.read_csv('campaign_master.csv')
print(len(campaign_master))
campaign_master.head()

3

  campaign_id campaign_name
0         CA1            éå¸¸
1         CA2         å¥ä¼è²»åé¡
2         CA3         å¥ä¼è²»ç¡æ

In [7]:
customer_join = pd.merge(customer,class_master, on="class",how="left")
customer_join = pd.merge(customer_join, campaign_master, on="campaign_id", how="left")
customer_join

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
2,OA974876,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
3,HD024127,XXXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
4,HD661448,XXXXX,C03,F,2015-05-01 00:00:00,NaN,CA1,0,ãã¤ã,6000,éå¸¸
...,...,...,...,...,...,...,...,...,...,...,...
4187,HD676663,XXXX,C01,M,2019-03-14 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
4188,HD246549,XXXXX,C01,F,2019-03-14 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
4189,GD037007,XXXXX,C03,M,2019-03-14 00:00:00,NaN,CA1,0,ãã¤ã,6000,éå¸¸
4190,OA953150,XXXXX,C01,M,2019-03-14 00:00:00,NaN,CA1,0,ãªã¼ã«ã¿ã¤ã,10500,éå¸¸
4191,IK692635,XXXXX,C02,F,2019-03-15 00:00:00,NaN,CA1,0,ãã¤ã¿ã¤ã,7500,éå¸¸

In [8]:
print(len(customer))
print(len(customer_join))

4192
4192

In [9]:
customer_join.isnull().sum()

customer_id         0
name                0
class               0
gender              0
start_date          0
end_date         2842
campaign_id         0
is_deleted          0
class_name          0
price               0
campaign_name       0
dtype: int64

In [11]:
customer_join.groupby("class_name").count()["customer_id"]

class_name
ãªã¼ã«ã¿ã¤ã     2045
ãã¤ã¿ã¤ã      1019
ãã¤ã       1128
Name: customer_id, dtype: int64

In [12]:
customer_join.groupby("campaign_name").count()["customer_id"]

campaign_name
å¥ä¼è²»åé¡     650
å¥ä¼è²»ç¡æ     492
éå¸¸       3050
Name: customer_id, dtype: int64

In [13]:
customer_join.groupby("gender").count()["customer_id"]

gender
F    1983
M    2209
Name: customer_id, dtype: int64

In [16]:

customer_join.groupby("is_deleted").count()["customer_id"]

is_deleted
0    2842
1    1350
Name: customer_id, dtype: int64

In [17]:
customer_join["start_date"] = pd.to_datetime(customer_join["start_date"])
customer_start = customer_join.loc[customer_join["start_date"]>pd.to_datetime("20180401")]
print(len(customer_start))

1361

In [20]:
customer_join["end_date"]=pd.to_datetime(customer_join["end_date"])
customer_newer = customer_join.loc[(customer_join["end_date"]>=pd.to_datetime("20190331"))|(customer_join["end_date"].isna())]
print(len(customer_newer))
customer_newer["end_date"].unique()

2953

array([                          'NaT', '2019-03-31T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [21]:
customer_newer.groupby("class_name").count()["customer_id"]

class_name
ãªã¼ã«ã¿ã¤ã     1444
ãã¤ã¿ã¤ã       696
ãã¤ã        813
Name: customer_id, dtype: int64

In [22]:
customer_newer.groupby("campaign_name").count()["customer_id"]

campaign_name
å¥ä¼è²»åé¡     311
å¥ä¼è²»ç¡æ     242
éå¸¸       2400
Name: customer_id, dtype: int64

In [23]:
customer_newer.groupby("gender").count()["customer_id"]

gender
F    1400
M    1553
Name: customer_id, dtype: int64